//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionClima.wservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clima", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Clima : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gradosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaHoraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                if ((object.ReferenceEquals(this.ciudadField, value) != true)) {
                    this.ciudadField = value;
                    this.RaisePropertyChanged("ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string grados {
            get {
                return this.gradosField;
            }
            set {
                if ((object.ReferenceEquals(this.gradosField, value) != true)) {
                    this.gradosField = value;
                    this.RaisePropertyChanged("grados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaHoraField, value) != true)) {
                    this.fechaHoraField = value;
                    this.RaisePropertyChanged("fechaHora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Maestro", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Maestro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wservice.control_climaSoap")]
    public interface control_climaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        AplicacionClima.wservice.ValidarUsuarioResponse ValidarUsuario(AplicacionClima.wservice.ValidarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ValidarUsuarioResponse> ValidarUsuarioAsync(AplicacionClima.wservice.ValidarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarClimasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarClimas", ReplyAction="*")]
        AplicacionClima.wservice.ListarClimasResponse ListarClimas(AplicacionClima.wservice.ListarClimasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarClimas", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ListarClimasResponse> ListarClimasAsync(AplicacionClima.wservice.ListarClimasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tabla del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarMaestro", ReplyAction="*")]
        AplicacionClima.wservice.ListarMaestroResponse ListarMaestro(AplicacionClima.wservice.ListarMaestroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarMaestro", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ListarMaestroResponse> ListarMaestroAsync(AplicacionClima.wservice.ListarMaestroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarClimaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarClima", ReplyAction="*")]
        AplicacionClima.wservice.ConsultarClimaResponse ConsultarClima(AplicacionClima.wservice.ConsultarClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarClima", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ConsultarClimaResponse> ConsultarClimaAsync(AplicacionClima.wservice.ConsultarClimaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clima del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearClima", ReplyAction="*")]
        AplicacionClima.wservice.CrearClimaResponse CrearClima(AplicacionClima.wservice.CrearClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearClima", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionClima.wservice.CrearClimaResponse> CrearClimaAsync(AplicacionClima.wservice.CrearClimaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RecuperarClimaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarClima", ReplyAction="*")]
        AplicacionClima.wservice.RecuperarClimaResponse RecuperarClima(AplicacionClima.wservice.RecuperarClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarClima", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionClima.wservice.RecuperarClimaResponse> RecuperarClimaAsync(AplicacionClima.wservice.RecuperarClimaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clima del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarClima", ReplyAction="*")]
        AplicacionClima.wservice.GuardarClimaResponse GuardarClima(AplicacionClima.wservice.GuardarClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarClima", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionClima.wservice.GuardarClimaResponse> GuardarClimaAsync(AplicacionClima.wservice.GuardarClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarClima", ReplyAction="*")]
        int EliminarClima(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarClima", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EliminarClimaAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ValidarUsuarioRequestBody Body;
        
        public ValidarUsuarioRequest() {
        }
        
        public ValidarUsuarioRequest(AplicacionClima.wservice.ValidarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public ValidarUsuarioRequestBody() {
        }
        
        public ValidarUsuarioRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ValidarUsuarioResponseBody Body;
        
        public ValidarUsuarioResponse() {
        }
        
        public ValidarUsuarioResponse(AplicacionClima.wservice.ValidarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ValidarUsuarioResult;
        
        public ValidarUsuarioResponseBody() {
        }
        
        public ValidarUsuarioResponseBody(int ValidarUsuarioResult) {
            this.ValidarUsuarioResult = ValidarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarClimasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarClimas", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ListarClimasRequestBody Body;
        
        public ListarClimasRequest() {
        }
        
        public ListarClimasRequest(AplicacionClima.wservice.ListarClimasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarClimasRequestBody {
        
        public ListarClimasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarClimasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarClimasResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ListarClimasResponseBody Body;
        
        public ListarClimasResponse() {
        }
        
        public ListarClimasResponse(AplicacionClima.wservice.ListarClimasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarClimasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionClima.wservice.Clima[] ListarClimasResult;
        
        public ListarClimasResponseBody() {
        }
        
        public ListarClimasResponseBody(AplicacionClima.wservice.Clima[] ListarClimasResult) {
            this.ListarClimasResult = ListarClimasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarMaestroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarMaestro", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ListarMaestroRequestBody Body;
        
        public ListarMaestroRequest() {
        }
        
        public ListarMaestroRequest(AplicacionClima.wservice.ListarMaestroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarMaestroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filtro;
        
        public ListarMaestroRequestBody() {
        }
        
        public ListarMaestroRequestBody(string tabla, string filtro) {
            this.tabla = tabla;
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarMaestroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarMaestroResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ListarMaestroResponseBody Body;
        
        public ListarMaestroResponse() {
        }
        
        public ListarMaestroResponse(AplicacionClima.wservice.ListarMaestroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarMaestroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionClima.wservice.Maestro[] ListarMaestroResult;
        
        public ListarMaestroResponseBody() {
        }
        
        public ListarMaestroResponseBody(AplicacionClima.wservice.Maestro[] ListarMaestroResult) {
            this.ListarMaestroResult = ListarMaestroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarClima", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ConsultarClimaRequestBody Body;
        
        public ConsultarClimaRequest() {
        }
        
        public ConsultarClimaRequest(AplicacionClima.wservice.ConsultarClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarClimaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ciudad;
        
        public ConsultarClimaRequestBody() {
        }
        
        public ConsultarClimaRequestBody(int ciudad) {
            this.ciudad = ciudad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.ConsultarClimaResponseBody Body;
        
        public ConsultarClimaResponse() {
        }
        
        public ConsultarClimaResponse(AplicacionClima.wservice.ConsultarClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionClima.wservice.Clima[] ConsultarClimaResult;
        
        public ConsultarClimaResponseBody() {
        }
        
        public ConsultarClimaResponseBody(AplicacionClima.wservice.Clima[] ConsultarClimaResult) {
            this.ConsultarClimaResult = ConsultarClimaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearClima", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.CrearClimaRequestBody Body;
        
        public CrearClimaRequest() {
        }
        
        public CrearClimaRequest(AplicacionClima.wservice.CrearClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearClimaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionClima.wservice.Clima clima;
        
        public CrearClimaRequestBody() {
        }
        
        public CrearClimaRequestBody(AplicacionClima.wservice.Clima clima) {
            this.clima = clima;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.CrearClimaResponseBody Body;
        
        public CrearClimaResponse() {
        }
        
        public CrearClimaResponse(AplicacionClima.wservice.CrearClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CrearClimaResult;
        
        public CrearClimaResponseBody() {
        }
        
        public CrearClimaResponseBody(int CrearClimaResult) {
            this.CrearClimaResult = CrearClimaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperarClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperarClima", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.RecuperarClimaRequestBody Body;
        
        public RecuperarClimaRequest() {
        }
        
        public RecuperarClimaRequest(AplicacionClima.wservice.RecuperarClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperarClimaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClima;
        
        public RecuperarClimaRequestBody() {
        }
        
        public RecuperarClimaRequestBody(int idClima) {
            this.idClima = idClima;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperarClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperarClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.RecuperarClimaResponseBody Body;
        
        public RecuperarClimaResponse() {
        }
        
        public RecuperarClimaResponse(AplicacionClima.wservice.RecuperarClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperarClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionClima.wservice.Clima[] RecuperarClimaResult;
        
        public RecuperarClimaResponseBody() {
        }
        
        public RecuperarClimaResponseBody(AplicacionClima.wservice.Clima[] RecuperarClimaResult) {
            this.RecuperarClimaResult = RecuperarClimaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarClima", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.GuardarClimaRequestBody Body;
        
        public GuardarClimaRequest() {
        }
        
        public GuardarClimaRequest(AplicacionClima.wservice.GuardarClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarClimaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionClima.wservice.Clima clima;
        
        public GuardarClimaRequestBody() {
        }
        
        public GuardarClimaRequestBody(AplicacionClima.wservice.Clima clima) {
            this.clima = clima;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionClima.wservice.GuardarClimaResponseBody Body;
        
        public GuardarClimaResponse() {
        }
        
        public GuardarClimaResponse(AplicacionClima.wservice.GuardarClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuardarClimaResult;
        
        public GuardarClimaResponseBody() {
        }
        
        public GuardarClimaResponseBody(int GuardarClimaResult) {
            this.GuardarClimaResult = GuardarClimaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface control_climaSoapChannel : AplicacionClima.wservice.control_climaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class control_climaSoapClient : System.ServiceModel.ClientBase<AplicacionClima.wservice.control_climaSoap>, AplicacionClima.wservice.control_climaSoap {
        
        public control_climaSoapClient() {
        }
        
        public control_climaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public control_climaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public control_climaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public control_climaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionClima.wservice.ValidarUsuarioResponse AplicacionClima.wservice.control_climaSoap.ValidarUsuario(AplicacionClima.wservice.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuario(request);
        }
        
        public int ValidarUsuario(string usuario, string contrasena) {
            AplicacionClima.wservice.ValidarUsuarioRequest inValue = new AplicacionClima.wservice.ValidarUsuarioRequest();
            inValue.Body = new AplicacionClima.wservice.ValidarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            AplicacionClima.wservice.ValidarUsuarioResponse retVal = ((AplicacionClima.wservice.control_climaSoap)(this)).ValidarUsuario(inValue);
            return retVal.Body.ValidarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ValidarUsuarioResponse> AplicacionClima.wservice.control_climaSoap.ValidarUsuarioAsync(AplicacionClima.wservice.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionClima.wservice.ValidarUsuarioResponse> ValidarUsuarioAsync(string usuario, string contrasena) {
            AplicacionClima.wservice.ValidarUsuarioRequest inValue = new AplicacionClima.wservice.ValidarUsuarioRequest();
            inValue.Body = new AplicacionClima.wservice.ValidarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((AplicacionClima.wservice.control_climaSoap)(this)).ValidarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionClima.wservice.ListarClimasResponse AplicacionClima.wservice.control_climaSoap.ListarClimas(AplicacionClima.wservice.ListarClimasRequest request) {
            return base.Channel.ListarClimas(request);
        }
        
        public AplicacionClima.wservice.Clima[] ListarClimas() {
            AplicacionClima.wservice.ListarClimasRequest inValue = new AplicacionClima.wservice.ListarClimasRequest();
            inValue.Body = new AplicacionClima.wservice.ListarClimasRequestBody();
            AplicacionClima.wservice.ListarClimasResponse retVal = ((AplicacionClima.wservice.control_climaSoap)(this)).ListarClimas(inValue);
            return retVal.Body.ListarClimasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ListarClimasResponse> AplicacionClima.wservice.control_climaSoap.ListarClimasAsync(AplicacionClima.wservice.ListarClimasRequest request) {
            return base.Channel.ListarClimasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionClima.wservice.ListarClimasResponse> ListarClimasAsync() {
            AplicacionClima.wservice.ListarClimasRequest inValue = new AplicacionClima.wservice.ListarClimasRequest();
            inValue.Body = new AplicacionClima.wservice.ListarClimasRequestBody();
            return ((AplicacionClima.wservice.control_climaSoap)(this)).ListarClimasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionClima.wservice.ListarMaestroResponse AplicacionClima.wservice.control_climaSoap.ListarMaestro(AplicacionClima.wservice.ListarMaestroRequest request) {
            return base.Channel.ListarMaestro(request);
        }
        
        public AplicacionClima.wservice.Maestro[] ListarMaestro(string tabla, string filtro) {
            AplicacionClima.wservice.ListarMaestroRequest inValue = new AplicacionClima.wservice.ListarMaestroRequest();
            inValue.Body = new AplicacionClima.wservice.ListarMaestroRequestBody();
            inValue.Body.tabla = tabla;
            inValue.Body.filtro = filtro;
            AplicacionClima.wservice.ListarMaestroResponse retVal = ((AplicacionClima.wservice.control_climaSoap)(this)).ListarMaestro(inValue);
            return retVal.Body.ListarMaestroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ListarMaestroResponse> AplicacionClima.wservice.control_climaSoap.ListarMaestroAsync(AplicacionClima.wservice.ListarMaestroRequest request) {
            return base.Channel.ListarMaestroAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionClima.wservice.ListarMaestroResponse> ListarMaestroAsync(string tabla, string filtro) {
            AplicacionClima.wservice.ListarMaestroRequest inValue = new AplicacionClima.wservice.ListarMaestroRequest();
            inValue.Body = new AplicacionClima.wservice.ListarMaestroRequestBody();
            inValue.Body.tabla = tabla;
            inValue.Body.filtro = filtro;
            return ((AplicacionClima.wservice.control_climaSoap)(this)).ListarMaestroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionClima.wservice.ConsultarClimaResponse AplicacionClima.wservice.control_climaSoap.ConsultarClima(AplicacionClima.wservice.ConsultarClimaRequest request) {
            return base.Channel.ConsultarClima(request);
        }
        
        public AplicacionClima.wservice.Clima[] ConsultarClima(int ciudad) {
            AplicacionClima.wservice.ConsultarClimaRequest inValue = new AplicacionClima.wservice.ConsultarClimaRequest();
            inValue.Body = new AplicacionClima.wservice.ConsultarClimaRequestBody();
            inValue.Body.ciudad = ciudad;
            AplicacionClima.wservice.ConsultarClimaResponse retVal = ((AplicacionClima.wservice.control_climaSoap)(this)).ConsultarClima(inValue);
            return retVal.Body.ConsultarClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionClima.wservice.ConsultarClimaResponse> AplicacionClima.wservice.control_climaSoap.ConsultarClimaAsync(AplicacionClima.wservice.ConsultarClimaRequest request) {
            return base.Channel.ConsultarClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionClima.wservice.ConsultarClimaResponse> ConsultarClimaAsync(int ciudad) {
            AplicacionClima.wservice.ConsultarClimaRequest inValue = new AplicacionClima.wservice.ConsultarClimaRequest();
            inValue.Body = new AplicacionClima.wservice.ConsultarClimaRequestBody();
            inValue.Body.ciudad = ciudad;
            return ((AplicacionClima.wservice.control_climaSoap)(this)).ConsultarClimaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionClima.wservice.CrearClimaResponse AplicacionClima.wservice.control_climaSoap.CrearClima(AplicacionClima.wservice.CrearClimaRequest request) {
            return base.Channel.CrearClima(request);
        }
        
        public int CrearClima(AplicacionClima.wservice.Clima clima) {
            AplicacionClima.wservice.CrearClimaRequest inValue = new AplicacionClima.wservice.CrearClimaRequest();
            inValue.Body = new AplicacionClima.wservice.CrearClimaRequestBody();
            inValue.Body.clima = clima;
            AplicacionClima.wservice.CrearClimaResponse retVal = ((AplicacionClima.wservice.control_climaSoap)(this)).CrearClima(inValue);
            return retVal.Body.CrearClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionClima.wservice.CrearClimaResponse> AplicacionClima.wservice.control_climaSoap.CrearClimaAsync(AplicacionClima.wservice.CrearClimaRequest request) {
            return base.Channel.CrearClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionClima.wservice.CrearClimaResponse> CrearClimaAsync(AplicacionClima.wservice.Clima clima) {
            AplicacionClima.wservice.CrearClimaRequest inValue = new AplicacionClima.wservice.CrearClimaRequest();
            inValue.Body = new AplicacionClima.wservice.CrearClimaRequestBody();
            inValue.Body.clima = clima;
            return ((AplicacionClima.wservice.control_climaSoap)(this)).CrearClimaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionClima.wservice.RecuperarClimaResponse AplicacionClima.wservice.control_climaSoap.RecuperarClima(AplicacionClima.wservice.RecuperarClimaRequest request) {
            return base.Channel.RecuperarClima(request);
        }
        
        public AplicacionClima.wservice.Clima[] RecuperarClima(int idClima) {
            AplicacionClima.wservice.RecuperarClimaRequest inValue = new AplicacionClima.wservice.RecuperarClimaRequest();
            inValue.Body = new AplicacionClima.wservice.RecuperarClimaRequestBody();
            inValue.Body.idClima = idClima;
            AplicacionClima.wservice.RecuperarClimaResponse retVal = ((AplicacionClima.wservice.control_climaSoap)(this)).RecuperarClima(inValue);
            return retVal.Body.RecuperarClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionClima.wservice.RecuperarClimaResponse> AplicacionClima.wservice.control_climaSoap.RecuperarClimaAsync(AplicacionClima.wservice.RecuperarClimaRequest request) {
            return base.Channel.RecuperarClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionClima.wservice.RecuperarClimaResponse> RecuperarClimaAsync(int idClima) {
            AplicacionClima.wservice.RecuperarClimaRequest inValue = new AplicacionClima.wservice.RecuperarClimaRequest();
            inValue.Body = new AplicacionClima.wservice.RecuperarClimaRequestBody();
            inValue.Body.idClima = idClima;
            return ((AplicacionClima.wservice.control_climaSoap)(this)).RecuperarClimaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionClima.wservice.GuardarClimaResponse AplicacionClima.wservice.control_climaSoap.GuardarClima(AplicacionClima.wservice.GuardarClimaRequest request) {
            return base.Channel.GuardarClima(request);
        }
        
        public int GuardarClima(AplicacionClima.wservice.Clima clima) {
            AplicacionClima.wservice.GuardarClimaRequest inValue = new AplicacionClima.wservice.GuardarClimaRequest();
            inValue.Body = new AplicacionClima.wservice.GuardarClimaRequestBody();
            inValue.Body.clima = clima;
            AplicacionClima.wservice.GuardarClimaResponse retVal = ((AplicacionClima.wservice.control_climaSoap)(this)).GuardarClima(inValue);
            return retVal.Body.GuardarClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionClima.wservice.GuardarClimaResponse> AplicacionClima.wservice.control_climaSoap.GuardarClimaAsync(AplicacionClima.wservice.GuardarClimaRequest request) {
            return base.Channel.GuardarClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionClima.wservice.GuardarClimaResponse> GuardarClimaAsync(AplicacionClima.wservice.Clima clima) {
            AplicacionClima.wservice.GuardarClimaRequest inValue = new AplicacionClima.wservice.GuardarClimaRequest();
            inValue.Body = new AplicacionClima.wservice.GuardarClimaRequestBody();
            inValue.Body.clima = clima;
            return ((AplicacionClima.wservice.control_climaSoap)(this)).GuardarClimaAsync(inValue);
        }
        
        public int EliminarClima(int id) {
            return base.Channel.EliminarClima(id);
        }
        
        public System.Threading.Tasks.Task<int> EliminarClimaAsync(int id) {
            return base.Channel.EliminarClimaAsync(id);
        }
    }
}
